version: '3.0'

services:
  postgres:
    image: postgres:latest
    container_name: 'postgres'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres_data:/data/test_db
    ports:
      - "5432:5432"
    restart: unless-stopped

