version: '3.0'

services:
  postgres:
    image: postgres:latest
    container_name: 'postgres'
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_USERNAME}
    volumes:
      - ./postgres_data:/data/${DB_NAME}
    ports:
      - "5432:5432"
    restart: unless-stopped

